- front-end/public/index.html
Reverts Premiurly/polkassembly#8
> Revert "google analytics"

- front-end/src/components/MenuBar/index.tsx
- front-end/src/components/MenuBar/query.ts
- front-end/src/generated/graphql.tsx
> Added latest block number

- auth-server/src/utils/messages.ts
- front-end/src/generated/graphql.tsx
- front-end/src/screens/Settings/index.tsx
- front-end/src/screens/Settings/multisig.tsx
- front-end/src/screens/Settings/query.ts
> Multisig frontend

- front-end/src/components/Listings/Members.tsx
- front-end/src/screens/Profile/CouncilVotes.tsx
- front-end/src/screens/Profile/index.tsx
> Added council votes

- front-end/src/screens/Settings/multisig.tsx
> multisig changes

- front-end/src/components/Login/Web2Login.tsx
- front-end/src/components/Login/Web3Login.tsx
- front-end/src/components/MenuBar/index.tsx
- front-end/src/components/Signup/Web2Signup.tsx
- front-end/src/components/Signup/Web3Signup.tsx
> Signup UI update : Active NavLink (loggedOutItems) colour, Signup and login buttons on auth pages

- auth-server/migrations/20220520102135_add_title_and_label.js
- auth-server/src/model/Profile.ts
- auth-server/src/resolvers/mutation/addProfile.ts
- auth-server/src/resolvers/query/userDetails.ts
- auth-server/src/schema/mutation/addProfile.ts
- auth-server/src/schema/type/profile.ts
- auth-server/src/types.ts
- front-end/src/components/queries.ts
- front-end/src/generated/graphql.tsx
Didn't run codegen due to absurd behaviour. It was removing some mutations.
> added insert image, bio and get user details

- front-end/src/components/Login/Web3Login.tsx
- front-end/src/components/Signup/Web3Signup.tsx
Reverts Premiurly/polkassembly#180
> Revert "bug fix for incorrect wallet showing on signup"

- front-end/src/components/Post/Poll/CouncilSignals.tsx
- front-end/src/components/Post/Poll/GeneralSignals.tsx
- front-end/src/components/Post/Poll/index.tsx
- front-end/src/components/Post/Post.tsx
- front-end/src/components/Post/PostContent.tsx
- front-end/src/components/Reactionbar/CommentReactionBar.tsx
- front-end/src/components/Reactionbar/LatestActivityPostReactions.tsx
- front-end/src/components/Reactionbar/PostReactionBar.tsx
- front-end/src/fragments/posts.ts
- front-end/src/generated/graphql.tsx
- front-end/src/screens/BountyPost/query.ts
- front-end/src/screens/CalendarView/index.tsx
- front-end/src/screens/DiscussionPost/query.ts
- front-end/src/screens/MotionPost/query.ts
- front-end/src/screens/ProposalPost/query.ts
- front-end/src/screens/ReferendumPost/query.ts
- front-end/src/screens/TechCommitteeProposalPost/query.ts
- front-end/src/screens/TreasuryPost/query.ts
- front-end/src/screens/UserProfile/index.tsx
Reverts Premiurly/polkassembly#234
> Revert "Revert "Timeline be""

- front-end/src/components/GovernanceCard.tsx
- front-end/src/components/Listing/Bounties/BountyListing.tsx
- front-end/src/components/Listing/ChildBounties/ChildBountyListing.tsx
- front-end/src/components/Listing/Motions/MotionsListing.tsx
- front-end/src/components/Listing/Proposals/ProposalsListing.tsx
- front-end/src/components/Listing/Referenda/ReferendaListing.tsx
- front-end/src/components/Listing/TechCommProposals/TechCommProposalsListing.tsx
- front-end/src/components/Listing/Tips/TipListing.tsx
- front-end/src/components/Listing/Treasury/TreasuryListing.tsx
> feat(Listing): like and dislike on listing card

- front-end/src/components/Post/Post.tsx
[sidebar-width.webm](https://user-images.githubusercontent.com/89686019/201476251-3677d24c-8fc1-4f5f-9349-cc48c30a6f49.webm)
> fix: post width expand when there is no governance sidebar

- front-end/package.json
- front-end/src/components/ContentForm.tsx
- front-end/src/ui-components/MarkdownEditor.tsx
- front-end/yarn.lock
[revert-text-editor.webm](https://user-images.githubusercontent.com/89686019/201986270-36a6a6dc-8758-45c2-a17e-c5ca65935ce2.webm)
> revert: text-editor

- front-end/src/components/AppLayout/NavHeader.tsx
- front-end/src/ui-components/GlobalStyle.tsx
- front-end/src/ui-components/Markdown.tsx
> Markdown formatting fix and other minor QA

- front-end/src/components/AppLayout/GovernanceSwitchButton.tsx
- front-end/src/components/AppLayout/SwitchRoutes.tsx
- front-end/src/components/AppLayout/index.tsx
- front-end/src/components/GovernanceCard.tsx
- front-end/src/components/Post/Tabs/PostOnChainInfo/PostReferendumV2Info.tsx
- front-end/src/components/PreImagesTable.tsx
- front-end/src/screens/PreImages/index.tsx
https://user-images.githubusercontent.com/48833948/203340579-2527d60e-cd42-4bfc-96d4-79f07cfdc4f7.mp4
> Gov2 Preimage

- front-end/src/components/Listing/Tracks/AboutTrackCard.tsx
- front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumV2VoteInfo.tsx
- front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumV2VotingStatus.tsx
- front-end/src/components/Post/GovernanceSideBar/Referenda/VotersList.tsx
- front-end/src/components/Post/GovernanceSideBar/index.tsx
- front-end/src/ui-components/Address.tsx
> Voting Status, display voters list for v2 referenda, About Track Card shows period as time

- front-end/src/components/AppLayout/index.tsx
> fix(Sidebar): removing list-style

- front-end/src/components/Post/Comment/EditableCommentContent.tsx
- front-end/src/components/Post/Comment/EditableReplyContent.tsx
[text-editor.webm](https://user-images.githubusercontent.com/89686019/205584355-5a6bca2b-4fa2-466a-8526-e7eb8689da5d.webm)
> fix: setting text editor initial state

- front-end/src/components/Balance/index.tsx
- front-end/src/components/Home/TreasuryOverview.tsx
- front-end/src/components/Listing/Tracks/DelegateModal.tsx
> FreeBalance fix

- front-end/src/screens/Listing/Discussions/index.tsx
> alignment of cta

- front-end/src/screens/Settings/Account/MultiSignatureAddress.tsx
[link-multisg.webm](https://user-images.githubusercontent.com/89686019/212086572-5e812662-69db-44d1-93f0-eba1fbeadd6a.webm)
> fix(LinkMultisig): link multisig, add account btn added

- front-end/src/components/Post/Post.tsx
- front-end/src/components/Post/PostHeading.tsx
> spend amount wherever available

- front-end/src/screens/Profile/CouncilVotes.tsx
- fix: subquery -> subsquid
- pagination fixes
> Voting history 
